### Normal Equation method to minimize cost function

Use the normal equation: Thetha = inv(X' * X) * X' * y<br>
Where X is the design matrix obtain by combining each sample data as a row and y is a vector of the class results

In [19]:
# Import packages
import numpy as np
import pandas as pd

In [20]:
inData = pd.read_csv('housingSample.csv')
inData

size  no_bedrooms  no_floors  age   price
0  2104            5          1   45  460000
1  1416            3          2   40  232000
2  1534            3          2   30  315000
3   852            2          1   36  178000

In [21]:
# Take training data excluding results
inData_train = inData.drop('price',axis = 1)
inData_train

size  no_bedrooms  no_floors  age
0  2104            5          1   45
1  1416            3          2   40
2  1534            3          2   30
3   852            2          1   36

In [22]:
# Store results in another vector
values = inData['price']
values

0    460000
1    232000
2    315000
3    178000
Name: price, dtype: int64

In [23]:
# Get the number of records
noRecords = inData_train.shape[0]
noRecords

4

In [24]:
# Get the number of features
noFeatures = inData_train.shape[1]
noFeatures

4

In [25]:
# Build an array of 1s for the X0 component
ones = np.ones((noRecords,1), dtype = int)
ones

array([[1],
       [1],
       [1],
       [1]])

In [26]:
# Obtain input dataframe as a numpy array for parsing
inData_array = inData_train.to_numpy()
inData_array

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [1534,    3,    2,   30],
       [ 852,    2,    1,   36]])

In [27]:
# Combine the 2 arrays
designMatrix = np.concatenate((ones,inData_array),axis = 1)
designMatrix

array([[   1, 2104,    5,    1,   45],
       [   1, 1416,    3,    2,   40],
       [   1, 1534,    3,    2,   30],
       [   1,  852,    2,    1,   36]])

In [28]:
# Assigning to matrix X for ease of processing
X = designMatrix
X

array([[   1, 2104,    5,    1,   45],
       [   1, 1416,    3,    2,   40],
       [   1, 1534,    3,    2,   30],
       [   1,  852,    2,    1,   36]])

In [29]:
# Tranpose of X
Xtranspose = X.T
Xtranspose

array([[   1,    1,    1,    1],
       [2104, 1416, 1534,  852],
       [   5,    3,    3,    2],
       [   1,    2,    2,    1],
       [  45,   40,   30,   36]])

In [30]:
# Product of X and X'
XXtranspose = np.matmul(X,Xtranspose)
XXtranspose

array([[4428868, 2981082, 3228904, 1794240],
       [2981082, 2006670, 2173358, 1207881],
       [3228904, 2173358, 2354070, 1308057],
       [1794240, 1207881, 1308057,  727206]])

In [31]:
# Inverse of XXtranspose
invXXtranspose = np.linalg.inv(XXtranspose)
invXXtranspose

array([[ 0.33066134,  0.98119962, -0.97584251, -0.69031411],
       [ 0.98119962, 13.65240949, -9.01520774, -8.88137341],
       [-0.97584251, -9.01520774,  6.36726544,  5.9287845 ],
       [-0.69031411, -8.88137341,  5.9287845 ,  5.79071723]])

In [32]:
# Multiplied by X'
invXXtransposeXtranspose = np.matmul(invXXtranspose,X.T)
invXXtransposeXtranspose

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)