### Normal Equation method to minimize cost function

Use the normal equation: Thetha = inv(X' * X) * X' * y<br>
Where X is the design matrix obtain by combining each sample data as a row and y is a vector of the class results

In [1]:
# Import packages
import numpy as np
import pandas as pd

In [2]:
inData = pd.read_csv('housingSample.csv')
inData

size  no_bedrooms  no_floors  age   price
0  2104            5          1   45  460000
1  1416            3          2   40  232000
2  1534            3          2   30  315000
3   852            2          1   36  178000

In [14]:
# Get the number of records
noRecords = inData.shape[0]
noRecords

4

In [15]:
# Get the number of features
noFeatures = inData.shape[1]
noFeatures

5

In [37]:
# Build an array of 1s for the X0 component
ones = np.ones((noRecords,1), dtype = int)
ones

array([[1],
       [1],
       [1],
       [1]])

In [38]:
# Obtain input dataframe as a numpy array for parsing
inData_array = inData.to_numpy()
inData_array

array([[  2104,      5,      1,     45, 460000],
       [  1416,      3,      2,     40, 232000],
       [  1534,      3,      2,     30, 315000],
       [   852,      2,      1,     36, 178000]])

In [39]:
# Combine the 2 arrays
designMatrix = np.concatenate((ones,inData_array),axis = 1)
designMatrix

array([[     1,   2104,      5,      1,     45, 460000],
       [     1,   1416,      3,      2,     40, 232000],
       [     1,   1534,      3,      2,     30, 315000],
       [     1,    852,      2,      1,     36, 178000]])

In [42]:
# Assigning to matrix X for ease of processing
X = designMatrix
X

array([[     1,   2104,      5,      1,     45, 460000],
       [     1,   1416,      3,      2,     40, 232000],
       [     1,   1534,      3,      2,     30, 315000],
       [     1,    852,      2,      1,     36, 178000]])

In [46]:
# Tranpose of X
Xtranspose = X.T
Xtranspose

array([[     1,      1,      1,      1],
       [  2104,   1416,   1534,    852],
       [     5,      3,      3,      2],
       [     1,      2,      2,      1],
       [    45,     40,     30,     36],
       [460000, 232000, 315000, 178000]])

In [47]:
# Product of X and X'
XXtranspose = np.matmul(X,Xtranspose)
XXtranspose

array([[211604428868, 106722981082, 144903228904,  81881794240],
       [106722981082,  53826006670,  73082173358,  41297207881],
       [144903228904,  73082173358,  99227354070,  56071308057],
       [ 81881794240,  41297207881,  56071308057,  31684727206]])

In [49]:
# Inverse of XXtranspose
invXXtranspose = np.linalg.inv(XXtranspose)
invXXtranspose

array([[ 0.27669707,  0.1246349 , -0.41980107, -0.13459896],
       [ 0.1246349 ,  0.05615813, -0.18917495, -0.06050916],
       [-0.41980107, -0.18917495,  0.63782823,  0.2027033 ],
       [-0.13459895, -0.06050916,  0.20270329,  0.06798936]])